name: tests

on:
  push:
    branches:
      - develop
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Set up just
      uses: ./.github/actions/setupjust

    - name: Install dependencies
      run: |
        just dev-sync

    - name: Run unit tests
      run: |
        just test
