# Copyright (c) 2025, NVIDIA CORPORATION.
# SPDX-License-Identifier: BSD-3-Clause
name: tests

on:
  push:
    branches:
      - develop
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[transforms]
      - name: Run unit tests
        run: |
          python -m unittest discover -s tests
